# Generated by Django 5.1.4 on 2025-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sequence', '0002_remove_midifile_uploaded_at_midifile_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midifile',
            name='fitness',
            field=models.IntegerField(blank=True),
        ),
    ]
