# Generated by Django 5.1.4 on 2025-01-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sequence', '0003_alter_midifile_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midifile',
            name='midi_file',
            field=models.FileField(help_text='Upload a valid MIDI file (.mid).', upload_to='melody/'),
        ),
    ]
