# Generated by Django 5.1.4 on 2025-01-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_sequence', '0004_alter_midifile_midi_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midifile',
            old_name='midi_file',
            new_name='audio',
        ),
    ]
