# Generated by Django 5.1.4 on 2025-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sequence', '0005_rename_midi_file_midifile_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='midifile',
            name='sequence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
